# Generated by Django 5.2.5 on 2025-08-06 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('company_name', models.CharField(help_text='Name of the hiring company', max_length=150)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('location', models.CharField(help_text='Job location (city, state, remote, etc.)', max_length=150)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when job was posted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job posting is active')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-posting_date'],
            },
        ),
    ]
