# Generated by Django 5.2.5 on 2025-08-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        help_text="Years of relevant experience"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("portfolio_url", models.URLField(blank=True, null=True)),
                (
                    "current_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "availability_date",
                    models.DateField(help_text="When can you start?"),
                ),
                ("willing_to_relocate", models.BooleanField(default=False)),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, help_text="Any additional information"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "email")},
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("job", "user_email")},
            },
        ),
    ]
